POST http://localhost:3000/api/posts HTTP/1.1

###

GET http://localhost:3000/api/posts HTTP/1.1

###

GET http://localhost:3000/api/posts/1 HTTP/1.1

###

PUT http://localhost:3000/api/posts/1 HTTP/1.1

###

DELETE http://localhost:3000/api/posts/1 HTTP/1.1

###
